layout_spectrum: 0.43713
favicon: null
name: stool
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 1
  lightness: 0.625
  saturation: 0.0625
  rhythmicContrast: 0.75
  brandColors:
    - '#020006'
    - '#7C8699'
    - '#E5E2E6'
    - '#B9B6BA'
    - '#443E47'
typography_spectrum: 0.1765957
