name: stool
favicon: null
layout_spectrum: 0.3737674586009234
typography_spectrum: 0.11151849781163037
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.6503211604431272
  lightness: 0.19806691887788475
  saturation: 0.1841639329213649
  rhythmicContrast: 0.4291029442101717
purpose: []
